# Generated by Django 5.2.1 on 2025-05-29 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchaseitem_vat_percent_purchaseitem_vat_value'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='supplier.supplier'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
