# Generated by Django 5.2.1 on 2025-06-01 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_supplier_delete_supplier'),
        ('purchase', '0003_alter_purchase_supplier_delete_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
