# Generated by Django 5.2.1 on 2025-06-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0003_remove_purchaseorder_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
