# Generated by Django 5.2.1 on 2025-06-02 10:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('product', '0008_alter_product_supplier_delete_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sale_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('total_vat', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('net_total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('available_quantity', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('vat_value', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sale.sale')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.unit')),
            ],
        ),
    ]
